<option value="Adak">Adak</option>
                                    <option value="Akiachak">Akiachak</option>
                                    <option value="Akiak">Akiak</option>
                                    <option value="Akutan">Akutan</option>
                                    <option value="Alakanuk">Alakanuk</option>
                                    <option value="Aleknagik">Aleknagik</option>
                                    <option value="Allakaket">Allakaket</option>
                                    <option value="Ambler">Ambler</option>
                                    <option value="Anaktuvuk Pass">Anaktuvuk Pass</option>
                                    <option value="Anchor Point">Anchor Point</option>
                                    <option value="Anchorage">Anchorage</option>
                                    <option value="Anderson">Anderson</option>
                                    <option value="Angoon">Angoon</option>
                                    <option value="Aniak">Aniak</option>
                                    <option value="Anvik">Anvik</option>
                                    <option value="Arctic Village">Arctic Village</option>
                                    <option value="Atka">Atka</option>
                                    <option value="Atqasuk">Atqasuk</option>
                                    <option value="Auke Bay">Auke Bay</option>
                                    <option value="Barrow">Barrow</option>
                                    <option value="Beaver">Beaver</option>
                                    <option value="Bethel">Bethel</option>
                                    <option value="Bettles Field">Bettles Field</option>
                                    <option value="Big Lake">Big Lake</option>
                                    <option value="Brevig Mission">Brevig Mission</option>
                                    <option value="Buckland">Buckland</option>
                                    <option value="Cantwell">Cantwell</option>
                                    <option value="Central">Central</option>
                                    <option value="Chalkyitsik">Chalkyitsik</option>
                                    <option value="Chefornak">Chefornak</option>
                                    <option value="Chevak">Chevak</option>
                                    <option value="Chicken">Chicken</option>
                                    <option value="Chignik">Chignik</option>
                                    <option value="Chignik Lagoon">Chignik Lagoon</option>
                                    <option value="Chignik Lake">Chignik Lake</option>
                                    <option value="Chitina">Chitina</option>
                                    <option value="Chugiak">Chugiak</option>
                                    <option value="Circle">Circle</option>
                                    <option value="Clam Gulch">Clam Gulch</option>
                                    <option value="Clarks Point">Clarks Point</option>
                                    <option value="Clear">Clear</option>
                                    <option value="Coffman Cove">Coffman Cove</option>
                                    <option value="Cold Bay">Cold Bay</option>
                                    <option value="Cooper Landing">Cooper Landing</option>
                                    <option value="Copper Center">Copper Center</option>
                                    <option value="Cordova">Cordova</option>
                                    <option value="Craig">Craig</option>
                                    <option value="Crooked Creek">Crooked Creek</option>
                                    <option value="Deering">Deering</option>
                                    <option value="Delta Junction">Delta Junction</option>
                                    <option value="Denali National Park">Denali National Park</option>
                                    <option value="Dillingham">Dillingham</option>
                                    <option value="Douglas">Douglas</option>
                                    <option value="Dutch Harbor">Dutch Harbor</option>
                                    <option value="Eagle">Eagle</option>
                                    <option value="Eagle River">Eagle River</option>
                                    <option value="Eek">Eek</option>
                                    <option value="Egegik">Egegik</option>
                                    <option value="Eielson AFB">Eielson AFB</option>
                                    <option value="Ekwok">Ekwok</option>
                                    <option value="Elfin Cove">Elfin Cove</option>
                                    <option value="Elim">Elim</option>
                                    <option value="Elmendorf AFB">Elmendorf AFB</option>
                                    <option value="Emmonak">Emmonak</option>
                                    <option value="Ester">Ester</option>
                                    <option value="Fairbanks">Fairbanks</option>
                                    <option value="False Pass">False Pass</option>
                                    <option value="Flat">Flat</option>
                                    <option value="Fort Richardson">Fort Richardson</option>
                                    <option value="Fort Wainwright">Fort Wainwright</option>
                                    <option value="Fort Yukon">Fort Yukon</option>
                                    <option value="Gakona">Gakona</option>
                                    <option value="Galena">Galena</option>
                                    <option value="Gambell">Gambell</option>
                                    <option value="Girdwood">Girdwood</option>
                                    <option value="Glennallen">Glennallen</option>
                                    <option value="Goodnews Bay">Goodnews Bay</option>
                                    <option value="Grayling">Grayling</option>
                                    <option value="Gustavus">Gustavus</option>
                                    <option value="Haines">Haines</option>
                                    <option value="Healy">Healy</option>
                                    <option value="Holy Cross">Holy Cross</option>
                                    <option value="Homer">Homer</option>
                                    <option value="Hoonah">Hoonah</option>
                                    <option value="Hooper Bay">Hooper Bay</option>
                                    <option value="Hope">Hope</option>
                                    <option value="Houston">Houston</option>
                                    <option value="Hughes">Hughes</option>
                                    <option value="Huslia">Huslia</option>
                                    <option value="Hydaburg">Hydaburg</option>
                                    <option value="Hyder">Hyder</option>
                                    <option value="Iliamna">Iliamna</option>
                                    <option value="Indian">Indian</option>
                                    <option value="Juneau">Juneau</option>
                                    <option value="Kake">Kake</option>
                                    <option value="Kaktovik">Kaktovik</option>
                                    <option value="Kalskag">Kalskag</option>
                                    <option value="Kaltag">Kaltag</option>
                                    <option value="Karluk">Karluk</option>
                                    <option value="Kasigluk">Kasigluk</option>
                                    <option value="Kasilof">Kasilof</option>
                                    <option value="Kenai">Kenai</option>
                                    <option value="Ketchikan">Ketchikan</option>
                                    <option value="Kiana">Kiana</option>
                                    <option value="King Cove">King Cove</option>
                                    <option value="King Salmon">King Salmon</option>
                                    <option value="Kipnuk">Kipnuk</option>
                                    <option value="Kivalina">Kivalina</option>
                                    <option value="Klawock">Klawock</option>
                                    <option value="Kobuk">Kobuk</option>
                                    <option value="Kodiak">Kodiak</option>
                                    <option value="Kotlik">Kotlik</option>
                                    <option value="Kotzebue">Kotzebue</option>
                                    <option value="Koyuk">Koyuk</option>
                                    <option value="Koyukuk">Koyukuk</option>
                                    <option value="Kwethluk">Kwethluk</option>
                                    <option value="Kwigillingok">Kwigillingok</option>
                                    <option value="Lake Minchumina">Lake Minchumina</option>
                                    <option value="Larsen Bay">Larsen Bay</option>
                                    <option value="Levelock">Levelock</option>
                                    <option value="Lower Kalskag">Lower Kalskag</option>
                                    <option value="Manley Hot Springs">Manley Hot Springs</option>
                                    <option value="Manokotak">Manokotak</option>
                                    <option value="Marshall">Marshall</option>
                                    <option value="Mc Grath">Mc Grath</option>
                                    <option value="Mekoryuk">Mekoryuk</option>
                                    <option value="Metlakatla">Metlakatla</option>
                                    <option value="Meyers Chuck">Meyers Chuck</option>
                                    <option value="Minto">Minto</option>
                                    <option value="Moose Pass">Moose Pass</option>
                                    <option value="Mountain Village">Mountain Village</option>
                                    <option value="Naknek">Naknek</option>
                                    <option value="Napakiak">Napakiak</option>
                                    <option value="Nenana">Nenana</option>
                                    <option value="New Stuyahok">New Stuyahok</option>
                                    <option value="Nightmute">Nightmute</option>
                                    <option value="Nikiski">Nikiski</option>
                                    <option value="Nikolai">Nikolai</option>
                                    <option value="Nikolski">Nikolski</option>
                                    <option value="Ninilchik">Ninilchik</option>
                                    <option value="Noatak">Noatak</option>
                                    <option value="Nome">Nome</option>
                                    <option value="Nondalton">Nondalton</option>
                                    <option value="Noorvik">Noorvik</option>
                                    <option value="North Pole">North Pole</option>
                                    <option value="Northway">Northway</option>
                                    <option value="Nuiqsut">Nuiqsut</option>
                                    <option value="Nulato">Nulato</option>
                                    <option value="Nunam Iqua">Nunam Iqua</option>
                                    <option value="Nunapitchuk">Nunapitchuk</option>
                                    <option value="Old Harbor">Old Harbor</option>
                                    <option value="Ouzinkie">Ouzinkie</option>
                                    <option value="Palmer">Palmer</option>
                                    <option value="Pedro Bay">Pedro Bay</option>
                                    <option value="Pelican">Pelican</option>
                                    <option value="Perryville">Perryville</option>
                                    <option value="Petersburg">Petersburg</option>
                                    <option value="Pilot Point">Pilot Point</option>
                                    <option value="Pilot Station">Pilot Station</option>
                                    <option value="Platinum">Platinum</option>
                                    <option value="Point Baker">Point Baker</option>
                                    <option value="Point Hope">Point Hope</option>
                                    <option value="Point Lay">Point Lay</option>
                                    <option value="Port Alexander">Port Alexander</option>
                                    <option value="Port Alsworth">Port Alsworth</option>
                                    <option value="Port Heiden">Port Heiden</option>
                                    <option value="Port Lions">Port Lions</option>
                                    <option value="Prudhoe Bay">Prudhoe Bay</option>
                                    <option value="Quinhagak">Quinhagak</option>
                                    <option value="Rampart">Rampart</option>
                                    <option value="Red Devil">Red Devil</option>
                                    <option value="Ruby">Ruby</option>
                                    <option value="Russian Mission">Russian Mission</option>
                                    <option value="Saint George Island">Saint George Island</option>
                                    <option value="Saint Marys">Saint Marys</option>
                                    <option value="Saint Michael">Saint Michael</option>
                                    <option value="Saint Paul Island">Saint Paul Island</option>
                                    <option value="Salcha">Salcha</option>
                                    <option value="Sand Point">Sand Point</option>
                                    <option value="Savoonga">Savoonga</option>
                                    <option value="Scammon Bay">Scammon Bay</option>
                                    <option value="Selawik">Selawik</option>
                                    <option value="Seldovia">Seldovia</option>
                                    <option value="Seward">Seward</option>
                                    <option value="Shageluk">Shageluk</option>
                                    <option value="Shaktoolik">Shaktoolik</option>
                                    <option value="Shishmaref">Shishmaref</option>
                                    <option value="Shungnak">Shungnak</option>
                                    <option value="Sitka">Sitka</option>
                                    <option value="Skagway">Skagway</option>
                                    <option value="Skwentna">Skwentna</option>
                                    <option value="Sleetmute">Sleetmute</option>
                                    <option value="Soldotna">Soldotna</option>
                                    <option value="South Naknek">South Naknek</option>
                                    <option value="Stebbins">Stebbins</option>
                                    <option value="Sterling">Sterling</option>
                                    <option value="Stevens Village">Stevens Village</option>
                                    <option value="Sutton">Sutton</option>
                                    <option value="Takotna">Takotna</option>
                                    <option value="Talkeetna">Talkeetna</option>
                                    <option value="Tanacross">Tanacross</option>
                                    <option value="Tanana">Tanana</option>
                                    <option value="Tatitlek">Tatitlek</option>
                                    <option value="Teller">Teller</option>
                                    <option value="Tenakee Springs">Tenakee Springs</option>
                                    <option value="Tetlin">Tetlin</option>
                                    <option value="Thorne Bay">Thorne Bay</option>
                                    <option value="Togiak">Togiak</option>
                                    <option value="Tok">Tok</option>
                                    <option value="Toksook Bay">Toksook Bay</option>
                                    <option value="Trapper Creek">Trapper Creek</option>
                                    <option value="Tuluksak">Tuluksak</option>
                                    <option value="Tuntutuliak">Tuntutuliak</option>
                                    <option value="Tununak">Tununak</option>
                                    <option value="Two Rivers">Two Rivers</option>
                                    <option value="Tyonek">Tyonek</option>
                                    <option value="Unalakleet">Unalakleet</option>
                                    <option value="Unalaska">Unalaska</option>
                                    <option value="Valdez">Valdez</option>
                                    <option value="Venetie">Venetie</option>
                                    <option value="Wainwright">Wainwright</option>
                                    <option value="Wales">Wales</option>
                                    <option value="Ward Cove">Ward Cove</option>
                                    <option value="Wasilla">Wasilla</option>
                                    <option value="White Mountain">White Mountain</option>
                                    <option value="Whittier">Whittier</option>
                                    <option value="Willow">Willow</option>
                                    <option value="Wrangell">Wrangell</option>
                                    <option value="Yakutat">Yakutat</option>